### ISSUE TITLE
Reliability/long-term durability

### ISSUE THREAD

**Issue by danielcompton** [cgrand/macrovich#3]
I'm interested in accepting a [PR](https://github.com/Day8/re-frame/pull/325) using macrovich, but am a bit concerned that upstream changes to Clojure/ClojureScript could break this library. Does macrovich depend on any internals of Clojure/ClojureScript that may change? Some of the namespace parsing code seemed like it might be a bit fragile?

**Comment by cgrand** [comment]
I can't predict the future :-)

First, I use macrovich.

Second, The regex-matching of the "pseudo-namespace' is only for self-hosted CLJS and both António Monteiro and Mike Fikes (who are pushing self host hard) are aware of macrovich (Mike provided me with expertise while I was porting xforms to cljc (and as a by-product spawned macrovich)).

**Comment by danielcompton** [comment]
Thanks, that's what I was after, no future predictions necessary.
