### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by arichiardi** [cgrand/macrovich#4]
Hi @cgrand,
thanks for this nice library!

I am using it in `honeysql` for porting to self-host and using it in some other project. I see that there are two hard dependencies on `clojure` and `clojurescript`, but I think those are more `:scope "provided"` dependencies than anything: at least `clojurescript`, which is only going to be necessary at compile/repl time and probably specified in user code.

I know this is a more general problem and probably I am getting it wrong - what I am doing now is to `:exclude` both of them so that they don't contribute to the classpath. Probably the new `clj` tool will actually help here in the future anyways.

I have opened this issue mainly to seek opinions and raise I doubt that I have always had: in all my current libs I set `[org.clojure/clojurescript ... :scope "test"]`...

:wave:

**Comment by cgrand** [comment]
It bothered me too, let's try with 0.2.1-SNAPSHOT
